---
- name: Run Docker Container on macOS
  hosts: localhost
  gather_facts: no
  vars:
      ansible_python_interpreter: /usr/local/bin/python3

  tasks:
    - name: Ensure Docker configuration directory exists
      file:
        path: "{{ ansible_env.HOME }}/.docker"
        state: directory
      become: yes

    - name: Copy Docker configuration file with credentials
      copy:
        src: path/to/your/config.json
        dest: "{{ ansible_env.HOME }}/.docker/config.json"
        mode: "0600"
      become: yes

    - name: Pull Docker Image
      community.docker.docker_image:
        name: spoider/pyth:v1.0
        source: pull

    - name: Run Docker Container
      community.docker.docker_container:
        name: my_container
        image: spoider/pyth:v1.0
        state: started
