---
- name: Run Docker Container on macOS
  hosts: localhost
  gather_facts: no  # Disable gathering facts since we're only running locally
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  tasks:
    - name: Pull Docker Image
      community.docker.docker_image:
        name: spoider/pyth:v1.0
        source: pull

    - name: Start Docker Service on macOS
      community.general.mac_service:
        name: com.docker.docker
        state: started

    - name: Run Docker Container
      shell: docker run -it spoider/pyth:v1.0
