---
- name: Pull docker image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull docker.io/spoider/pyth:v1.0
      
    - name: running container
      shell: docker run -it spoider/pyth:v1.0