---
- name: Pull and run a Docker container
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  tasks:
    - name: Pull Docker image
        command: docker pull spoider/pyth:v1.0

    - name: Run Docker container
      community.docker.docker_container:
        name: my_calculator_container
        image: spoider/pyth:v1.0
        state: started
