---
- name: Manage Docker Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: spoider/pyth:v1.0
        source: pull
    -name: start docker service
      service: docker
      state: started

    -name: Run Docker container
     shell: docker run -it spoider/pyth
