---
- name: Pull docker image of Calculator
  hosts: localhost
  tasks:

    - name: Start docker service
      systemd:
        name: docker
        state: started
        enabled: yes
        
    - name: pull docker image
      shell: docker pull docker.io/spoider/pyth:v1.0
      
    - name: running container
      shell: docker run -it spoider/pyth:v1.0
      