---
- name: Pull docker image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  tasks:

    - name: pull docker image
       community.docker.docker_image:
        name: spoider/pyth:v1.0

    - name: Run Docker container
      community.docker.docker_container:
        name: my_calculator_container
        image: spoider/pyth:v1.0
        state: started
      